[tools]
"cargo:mq-run" = "0.5.24"
"cargo:pipe-rename" = "1.6.7"
powershell = "7.6.1"
regctl = "0.11.3"
regsync = "0.11.3"
usage = "3.2.1"

[settings]
#locked = true
lockfile = true
cargo.binstall = true
