[tools]
"cargo:mq-run" = "0.6.0"
"cargo:pipe-rename" = "1.6.7"
powershell = "7.6.3"
rclone = "1.74.3"
regctl = "0.11.5"
regsync = "0.11.5"
restic = "0.19.0"
usage = "3.5.2"

[settings]
lockfile = true
cargo.binstall = true
