---
name: "Config checks"

on:
  push:
    branches:
      - "**"
  pull_request: ~

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  test-config:
    name: "Test configuration"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
        with:
          persist-credentials: false

      - name: "Run actionlint"
        uses: "reviewdog/action-actionlint@dbe5299849118fd6f099ba563d263d770955a64a" # v1.73.2
        with:
          fail_level: "warning"

      - name: "Run zizmor"
        uses: "zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054" # v0.6.2
        with:
          advanced-security: false
          annotations: true

      - name: "Run gitleaks"
        uses: "reviewdog/action-gitleaks@2b7b5685e3e3eecddab5d30cfa04f18123031421" # v1.8.0
        with:
          fail_level: "warning"

      - name: "Check Renovatebot config"
        uses: "docker://ghcr.io/renovatebot/renovate@sha256:0c8122ec80a90963fde9609d5b8396a4fcafa53504ebf5ac32ff8097c2f05f98" # v43.177
        with:
          args: "renovate-config-validator --strict"

      - name: "Run shellcheck"
        uses: "reviewdog/action-shellcheck@0722bbdb0d47f04c1b53b8734d2422ac63a45ec6" # v1.32.1
        with:
          fail_level: "info"
          shellcheck_flags: ""
