---
name: "Config checks"

on:
  push:
    branches:
      - "**"
  pull_request: ~

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  test-config:
    name: "Test configuration"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
        with:
          persist-credentials: false

      - name: "Run actionlint"
        uses: "reviewdog/action-actionlint@320fcdd9c860767cf17fab3b20e22e739d5d02b8" # v1.76.0
        with:
          fail_level: "warning"

      - name: "Run zizmor"
        uses: "zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482" # v0.6.4
        with:
          advanced-security: false
          annotations: true

      - name: "Run gitleaks"
        uses: "reviewdog/action-gitleaks@2b7b5685e3e3eecddab5d30cfa04f18123031421" # v1.8.0
        with:
          fail_level: "warning"

      - name: "Check Renovatebot config"
        uses: "docker://ghcr.io/renovatebot/renovate@sha256:0c8122ec80a90963fde9609d5b8396a4fcafa53504ebf5ac32ff8097c2f05f98" # v43.177
        with:
          args: "renovate-config-validator --strict"

      - name: "Run shellcheck"
        uses: "reviewdog/action-shellcheck@0a90156c6e0553996a217f0a9e09be6b0f6bee4c" # v1.34.0
        with:
          fail_level: "info"
          shellcheck_flags: ""
