---
name: "Config checks"

on:
  push:
    branches:
      - "**"
  pull_request: ~

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  test-config:
    name: "Test configuration"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
        with:
          persist-credentials: false

      - name: "Run actionlint"
        uses: "reviewdog/action-actionlint@50842263c20a7c46bd0065b9e624d3c569db061e" # v1.73.0
        with:
          fail_level: "warning"

      - name: "Run zizmor"
        uses: "zizmorcore/zizmor-action@6fc4b006235f201fdab3722e17240ab420d580e5" # v0.6.1
        with:
          advanced-security: false
          annotations: true

      - name: "Run gitleaks"
        uses: "reviewdog/action-gitleaks@2b7b5685e3e3eecddab5d30cfa04f18123031421" # v1.8.0
        with:
          fail_level: "warning"

      - name: "Check Renovatebot config"
        uses: "docker://ghcr.io/renovatebot/renovate@sha256:0c8122ec80a90963fde9609d5b8396a4fcafa53504ebf5ac32ff8097c2f05f98" # v43.177
        with:
          args: "renovate-config-validator --strict"

      - name: "Run shellcheck"
        uses: "reviewdog/action-shellcheck@4c07458293ac342d477251099501a718ae5ef86e" # v1.32.0
        with:
          fail_level: "info"
          shellcheck_flags: ""
